# Generated by Django 6.0.3 on 2026-04-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_fr', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('head_name', models.CharField(blank=True, max_length=200)),
                ('head_title_fr', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(default='fas fa-building', max_length=50)),
                ('color', models.CharField(default='#2d1b69', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unité Administrative',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Numéro')),
                ('name_fr', models.CharField(max_length=200, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Nom (EN)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Nom (AR)')),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('population', models.PositiveIntegerField(default=0)),
                ('area_km2', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mayor_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='arrondissements/')),
                ('color', models.CharField(default='#003580', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arrondissement',
                'verbose_name_plural': 'Arrondissements',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_fr', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('description_fr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('icon', models.CharField(default='fas fa-cog', max_length=50)),
                ('color', models.CharField(default='#003580', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie de service',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_fr', models.CharField(max_length=400)),
                ('message_en', models.CharField(blank=True, max_length=400)),
                ('message_ar', models.CharField(blank=True, max_length=400)),
                ('icon', models.CharField(default='📢', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AgendaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=300)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('title_ar', models.CharField(blank=True, max_length=300)),
                ('description_fr', models.TextField(blank=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=300)),
                ('category', models.CharField(default='Général', max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrondissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.arrondissement')),
            ],
            options={
                'verbose_name': 'Événement',
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=400)),
                ('title_en', models.CharField(blank=True, max_length=400)),
                ('title_ar', models.CharField(blank=True, max_length=400)),
                ('excerpt_fr', models.TextField(max_length=500)),
                ('excerpt_en', models.TextField(blank=True, max_length=500)),
                ('excerpt_ar', models.TextField(blank=True, max_length=500)),
                ('content_fr', models.TextField()),
                ('content_en', models.TextField(blank=True)),
                ('content_ar', models.TextField(blank=True)),
                ('category', models.CharField(default='Général', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrondissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.arrondissement')),
            ],
            options={
                'verbose_name_plural': 'Actualités',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=300)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('title_ar', models.CharField(blank=True, max_length=300)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('requirements_fr', models.TextField(blank=True, help_text='Liste des pièces, une par ligne')),
                ('steps_fr', models.TextField(blank=True, help_text='Étapes, une par ligne')),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('fees', models.CharField(blank=True, max_length=100)),
                ('office', models.CharField(blank=True, max_length=200)),
                ('is_online', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicecategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
